### ISSUE TITLE
Crashes bcrypt

### ISSUE THREAD

**Issue by olalonde** [tinylibs/tinypool#48] opened 2023-02-28 16:34 UTC
https://github.com/kelektiv/node.bcrypt.js/issues/980

I'm not really sure what this library does and whether it's a bug that can be fixed by bcrypt or tinypool.

**Comment by Aslemammad** [comment] 2023-03-12 13:28
Interesting, what do these libraries have in common, that makes the problem related to Tinypool? Do you have any reproductions (not with vitest, with Tinypool only)

**Comment by Aslemammad** [comment] 2023-03-12 13:29
Interesting, what do these libraries have in common, that makes the problem related to Tinypool? Do you have any reproductions (not with vitest, with Tinypool only)

**Comment by olalonde** [comment] 2023-03-12 18:18
No I don't have a reproduction but the reason that leads me to believe it's an issue with tinypool:

1) I get the error using two different native libraries (the only thing they have in common is that they're native libraries AFAIK)

2) the error only happens when threading is enabled on vitest

**Comment by olalonde** [comment] 2023-03-12 18:20
It could also be a bug in some library that tinypool is using, including Node.js implementation of `worker_threads` ?

**Comment by Aslemammad** [comment] 2023-03-12 18:55
maybe, I don't think Tinypool is doing something different, it uses `worker_threads`! So the issue may be there, and if it is, then the issue is mostly with the libs.

**Comment by olalonde** [comment] 2023-03-12 21:31
Or maybe https://nodejs.org/api/async_hooks.html ? It's marked as an experimental API. I'll see if I can isolate the bug.

**Comment by Aslemammad** [comment] 2023-03-13 07:53
That'd help so much

**Comment by AriPerkkio** [comment] 2023-10-04 04:58
Fixed by https://github.com/tinylibs/tinypool/issues/64.

**Closed by AriPerkkio** 2023-10-04 04:58 UTC
