### ISSUE TITLE
Error with NODE_OPTIONS

### ISSUE THREAD

**Issue by hupling** [tinylibs/tinypool#59] opened 2023-06-09 06:37 UTC
I set the environment variable `NODE_OPTIONS: -use-openssl-ca`
```
> vitest run
 RUN  v0.20.3 /builds/xxx/frontend
⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯
Error: Initiated Worker with invalid NODE_OPTIONS env variable: --use-openssl-ca is not allowed in NODE_OPTIONS
 ❯ new NodeError node:internal/errors:387:5
 ❯ new Worker node:internal/worker:198:13
 ❯ ThreadPool._addNewWorker node_modules/tinypool/dist/esm/index.js:500:20
 ❯ ThreadPool._ensureMinimumWorkers node_modules/tinypool/dist/esm/index.js:485:12
 ❯ new ThreadPool node_modules/tinypool/dist/esm/index.js:475:10
 ❯ new Tinypool node_modules/tinypool/dist/esm/index.js:739:31
 ❯ createPool node_modules/vitest/dist/chunk-vite-node-externalize.91ae6e85.mjs:7044:16
 ❯ node_modules/vitest/dist/chunk-vite-node-externalize.91ae6e85.mjs:9504:21
 ❯ Vitest.runFiles node_modules/vitest/dist/chunk-vite-node-externalize.91ae6e85.mjs:9521:7
 ❯ Vitest.start node_modules/vitest/dist/chunk-vite-node-externalize.91ae6e85.mjs:9442:5
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Serialized Error: {
  "code": "ERR_WORKER_INVALID_EXEC_ARGV",
```
 
 You should not put the environment variable NODE_OPTIONS to the child process. It is automatically taken from the parent.

 >       // Only fail for explicitly provided env, this protects from failures
 >      // when NODE_OPTIONS from parent's env is used (which is the default).

https://github.com/nodejs/node/blob/v16.20.0/src/node_worker.cc#L513-L514

**Comment by Aslemammad** [comment] 2023-06-09 11:42
cc @sheremet-va is it vitest related?

**Comment by sheremet-va** [comment] 2023-06-09 11:45
> cc @sheremet-va is it vitest related?

Yes, looks like it’s Vitest related. The version is too old though.

**Comment by eidottermihi** [comment] 2023-06-12 07:40
This also occurs with latest vitest (0.32.0) which uses latest tinypool (0.5.0):

```
$ NODE_OPTIONS=--use-openssl-ca npm run test

> myproject@4.0.0 test
> vitest


 DEV  v0.32.0 C:/Users/michael.prankl/git/myproject


Unhandled Errors 
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Vitest caught 1 unhandled error during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.

⎯⎯⎯⎯⎯⎯⎯⎯Unhandled Error Error: Initiated Worker with invalid NODE_OPTIONS env variable: --use-openssl-ca is not allowed in NODE_OPTIONS
 ❯ new NodeError node:internal/errors:399:5
 ❯ new Worker node:internal/worker:205:13
 ❯ ThreadPool._addNewWorker node_modules/tinypool/dist/esm/index.js:533:20
 ❯ ThreadPool._ensureMinimumWorkers node_modules/tinypool/dist/esm/index.js:518:12
 ❯ new ThreadPool node_modules/tinypool/dist/esm/index.js:503:10
 ❯ new Tinypool node_modules/tinypool/dist/esm/index.js:772:31
 ❯ createThreadsPool node_modules/vitest/dist/vendor-cli-api.897427d4.js:7213:16
 ❯ node_modules/vitest/dist/vendor-cli-api.897427d4.js:7442:43
 ❯ Object.runTests node_modules/vitest/dist/vendor-cli-api.897427d4.js:7434:51

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯Serialized Error: {
  "code": "ERR_WORKER_INVALID_EXEC_ARGV",
}
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
 Test Files  no tests
      Tests  no tests
     Errors  1 error
   Start at  09:38:23
   Duration  70ms (transform 0ms, setup 0ms, collect 0ms, tests 0ms, environment 0ms, prepare 0ms)
 ```

**Comment by hupling** [comment] 2023-06-13 06:58
I will use `NODE_EXTRA_CA_CERTS`

**Comment by eidottermihi** [comment] 2023-06-13 07:21
@hupling 

> I will use NODE_EXTRA_CA_CERTS

thats a possible workaround, yes. But the issue still remains, could you please reopen the issue? 

https://nodejs.org/api/cli.html#node_optionsoptions clearly says that `--use-openssl-ca` is a valid option, so this error shouldn't occur IMHO.

**Comment by Aslemammad** [comment] 2023-06-13 07:48
The thing is tinypool does not control this, but vitest does at its side, but let's have this issue open so @sheremet-va can watch it.

**Comment by AriPerkkio** [comment] 2023-06-16 11:32
Slightly related to https://github.com/vitest-dev/vitest/pull/2702 where similar Node exec argv filtering is done to ensure workers are not passed incompatible options.

**Comment by AriPerkkio** [comment] 2024-01-21 18:06
Fixed by https://github.com/vitest-dev/vitest/pull/2702. Vitest no longer passes all arguments to Tinypool.

There's nowadays another way to pass explicit exec argv to workers: https://github.com/vitest-dev/vitest/pull/4383.

**Closed by AriPerkkio** 2024-01-21 18:06 UTC
Labels: bug, help wanted

**Comment by clemyan** [comment] 2026-03-19 13:23
Not sure if this is a regression or was never fixed, but currently `NODE_OPTIONS` is not inherited by the child process. In fact, no environment variables are inherited unless `env: process.env` is explicitly passed to the `TinyPool` constructor.

In particular, ESM loaders that are intended to be inherited by child processes are set up using `NODE_OPTIONS` and this breaks those loaders.

**Comment by AriPerkkio** [comment] 2026-03-19 13:50
This package never passed `NODE_OPTIONS` unless user explicitly did that.

`tinypool@0.0.1`:

https://github.com/tinylibs/tinypool/blob/adbffcdfda18baad6ad694228436f615f1d67b86/src/index.ts#L598-L599

**Comment by AriPerkkio** [comment] 2026-03-19 13:52
> In particular, ESM loaders that are intended to be inherited by child processes are set up using `NODE_OPTIONS` and this breaks those loaders.

As this package also supports `node:worker_threads`, I guess you would also run into this issue when not specifying `.env`:
-  https://github.com/nodejs/node/issues/62301

**Comment by clemyan** [comment] 2026-03-19 15:25
> This package never passed NODE_OPTIONS unless user explicitly did that.

So this is "working as intended"? Should this be documented? Environment variables (`NODE_OPTIONS` in particular) are intended to pierce the process tree to affect all sub-processes and I don't see a compelling reason why `tinypool` should not support that. The default behavior will break a lot of things: ESM loaders, VSCode debugger auto attach, some code coverage tools, permissions model, etc.

> As this package also supports node:worker_threads, I guess you would also run into this issue when not specifying .env:

[Yes, I am aware](https://github.com/nodejs/node/issues/37410)

**Comment by AriPerkkio** [comment] 2026-03-19 15:34
Looking at `piscina` which this project is a fork of, it looks like this behaviour is inherited from there. 

https://github.com/piscinajs/piscina/blob/current/src/index.ts#L238-L240

I'm not sure why, but maybe it's related to the fact that some flags may crash workers even when they work on main thread. You might want to open issue on Piscina to get reason for this. 🤔
